name: Noir

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Noir toolchain
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: nightly
    - name: Run tests
      run: |
        nargo test
    - name: Prove examples
      run: |
        nargo prove --workspace
    - name: Verify examples
      run: |
        nargo verify --workspace
